name: Deploy to Salmon-Flower

on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: prepare build date in GITHUB_ENV
        id: step_build_date_and_time
        run: |
          echo "build_timestamp=$(date)" >> $GITHUB_ENV
        
      - name: Use the build date from GITHUB_ENV
        id: step_replace
        # encode connection string with https://dwaves.de/tools/escape/ !!
        run: |
          echo "build timestamp: ${{ env.build_timestamp }}"
          echo "run number: ${{ github.run_number }}"
          sed -i 's/__BUILDDATE__/${{ env.build_timestamp }} (build ${{ github.run_number }})/g' firewall-mon-app/src/environments/environment.prod.ts 
          sed -i 's/__APPLICATION_INSIGHTS_CONNECTION_STRING__/${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}/g' firewall-mon-app/src/environments/environment.prod.ts 
          cat firewall-mon-app/src/environments/environment.prod.ts

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FLOWER_01D41A203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/firewall-mon-app/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/firewall-mon-app" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FLOWER_01D41A203 }}
          action: "close"
